#! /usr/bin/perl
# Chapter_5
# April_2_2013
use warnings;
use strict ;
@ARGV = qw /chapter_5/;
print reverse <>;
#----- 8 -- 9
print "What column width would you like ,puppy ?\n";
chomp (my $width = <>);

print "\n"."Please input something ,and press Ctrl - Z to exit input .\n";

chomp(my @lines = <STDIN>); #Change lenght of number rule based on input 
    
print "1234567890" x (($width + 9)/10), (1..5)."\n";#it's cool ;
my $format = "%${width}s\n" x @lines;
printf $format , @lines; 
