#! /usr/bin/perl
# Chapter_9
# April_5_2013
use warnings;
use strict ;
open FILE, "README.md" or die "Can't open 'README.md' : $!";
my $lines = join '', <FILE>;
$lines =~ s/^README.md://gm;
#print $lines;
close FILE;
my $date = localtime ;
$^I = ".bak";
@ARGV = qw/README.md/;
while(<>){
    #s/^/--/;
    s/^Author:.*/Author: a.c.God/;
    s/^Date:.*/Date: $date/;
    print;
}


