#! /usr/bin/perl -w
=mit
A common security method used for online banking is to ask the user for three random characters from a passcode. For example, if the passcode was 531278, they may ask for the 2nd, 3rd, and 5th characters; the expected reply would be: 317.

The text file, keylog.txt, contains fifty successful login attempts.

Given that the three characters are always asked for in order, analyse the file so as to determine the shortest possible secret passcode of unknown length.
=cut

use 5.014;
use strict;
say "Do some analysis first .";
open File ,'<',"keylog.txt" or die "Oops ! I am dying ...$!";
my %pomegranate ;
my %tulip ;
my @valid_num = (0,1,2,3,6,7,8,9);
map{
    $tulip{$_} = 10;
}@valid_num;

while(<File>){
    chomp;
    my @ponyo = split //;
    map{
	$pomegranate{$_} += 1 if defined($pomegranate{$_});
	$pomegranate{$_} = 1 if !defined($pomegranate{$_});
    }@ponyo;

    map{
	my ($ex,$ne) = ($ponyo[$_], $ponyo[$_+1]);
	$tulip{$ne} = ($tulip{$ne} < $tulip{$ex} - 1) ? $tulip{$ne} : $tulip{$ex} - 1;
    }(0..1);
}

map{
    say "< $_, ",$tulip{$_}," >";
}keys %tulip;

%tulip = reverse %tulip;
say "The ans is = ";
map{
    print $tulip{$_};
}(sort{$b<=>$a} keys %tulip);

say "\n--------------------------------";

map{
    printf "%3s : %3s\n",$_, $pomegranate{$_};
}(sort keys %pomegranate);

say "--------------------------------";
