#!/usr/bin/perl -w 
use strict ;
use 5.010;
=block
    The first known prime found to exceed one million digits was discovered in 1999, and is a Mersenne prime of the form 269725931; it contains exactly 2,098,960 digits. Subsequently other Mersenne primes, of the form 2p1, have been found which contain more digits.

However, in 2004 there was found a massive non-Mersenne prime which contains 2,357,207 digits: 28433*2^7830457+1.

Find the last ten digits of this prime number.
=cut    
say "---------------------------------------------- Section 1.";
my $index = 7830457;
my $factor = 28433;
my $lotus = 1 ;
map{
    $lotus = ($lotus*2) % (10**10);
}(1..$index);

$lotus = ($lotus*$factor+1) % (10**10);


say "Fianl result : ",$lotus ;

